conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'


urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'), 
]

item/urls.py
from django.urls import path, include
from . import views


# URL Patterns
app_name = 'item'
urlpatterns = [
    path('', views.browse_items, name='browse_items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

pamusika/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('pamusika_web_market.urls')),
    path('items/',include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('admin/', admin.site.urls),
]

pamusika_web_market/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from . forms import LoginForm


# URL Patterns
app_name = 'pamusika_web_market'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name ='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='pamusika_web_market/login.html', authentication_form=LoginForm), name='login'),
]


pamusika_web_market/models.py
from django.db import models

# Create your models here.

pamusika_web_market/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


# creating a form classes
class LoginForm(AuthenticationForm):
    """This  class inherits from django.contrib.auth.forms to create a custom form object for Login
    class directly inherits from AuthenticationForm
    """
    # customising form fields
    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'username',
            'class': 'form-control',
            'id': 'floatingInput',
        
        }))
    
    password = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'password',
            'class': 'form-control',
            'id': 'floatingInput',
        
        }))


class SignupForm(UserCreationForm):
    """This  class inherits from django.contrib.auth.forms to create a custom form object for Login
    class directly inherits from UserCreationForm
    """
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    # customising form fields
    username = forms.CharField(widget=forms.TextInput(attrs={
            'placeholder': 'username',
            'class': 'form-control',
            'id': 'floatingInput',
        
        }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
            'placeholder': 'name@example.com',
            'class': 'form-control',
            'id': 'floatingInput',
        
        }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'password',
            'class': 'form-control',
            'id': 'floatingInput',
        
        }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
            'placeholder': 'passeord',
            'class': 'form-control',
            'id': 'floatingInput',
        
        }))

pamusika_web_market/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from . forms import SignupForm

# Pamusika Web Market Views
def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')[0:6]
    categories = Category.objects.all()

    return render(request, 'pamusika_web_market/index.html', {
        'categories': categories,
        'items': items
    })

def contact(request):
    return render(request, 'pamusika_web_market/contact.html')

def signup(request):
    # handling submitting of signup form
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
    else:
        form = SignupForm()
        
    form = SignupForm()

    return render(request, 'pamusika_web_market/signup.html', {'form': form})

#def newitem(request)

templates/pamusika_web_market/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <title>Pamusika Web Market | {% block title %} {% endblock%}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom_styles.css' %}" rel="stylesheet">
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body id="body">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Pamusika</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav me-auto mb-2 mb-md-0">
                </div>
                <div class="d-flex">
                    <ul class="navbar-nav me-auto mb-2">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'pamusika_web_market:index' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'item:new' %}">New Item</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'item:browse_items' %}">Browse</a>
                        </li>
                    </ul>
                    <div class="row navbar-nav">
                        {% if request.user.is_authenticated %}
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-5 nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'conversation:inbox' %}">
                                <button class=" btn-lg btn-primary ">Inbox</button>
                            </a>
                        </div>

                        <div class="col-lg-5 nav-item">
                            <a class="nav-link" href="{% url 'dashboard:index' %}">
                                <button class=" btn-lg btn-secondary">Dashboard</button>
                            </a>
                        </div>
                        {% else %}
                        <div class="col-lg-1">
                        </div>
                        <div class="col-lg-5 nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'pamusika_web_market:signup' %}">
                                <button class=" btn-lg btn-primary ">Signup</button>
                            </a>
                        </div>

                        <div class="col-lg-5 nav-item">
                            <a class="nav-link" href="{% url 'pamusika_web_market:login' %}">
                                <button class=" btn-lg btn-success">Login</button>
                            </a>
                        </div>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </nav>

        {% block content %}

        {% endblock %}

    <footer class="footer  bg-dark text-muted">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row text-secondary">
                        <h5>About</h5>
                    </div>
                    <div class="row">
                        <div class="text-grey">
                            <p>
                                Ipsum hbnalsccp ajlcnas nkvgs ihasjkjnklas jjd  ahjsap
                                Lorem Ipsum hbnalsccp ajlcnas nkvgs ihasjkjnklas jjd  ahjsap
                                Lorem Ipsum hbnalsccp ajlcnas nkvgs ihasjkjnklas jjd  ahjsap
                                Lorem Ipsum hbnalsccp ajlcnas nkvgs ihasjkjnklas jjd  ahjsap
                            </p>
                        </div>

                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-8">

                            </div>
                            <div class="col-6 col-md-2 mb-3">
                                <h5 class="text-secondary">Menu</h5>
                                <ul class="nav flex-column">
                                    <li class="nav-item mb-2"><a href="{% url 'pamusika_web_market:index'%}" class="nav-link p-0 text-muted">Home</a></li>
                                    <li class="nav-item mb-2"><a href="{% url 'pamusika_web_market:contact'%}" class="nav-link p-0 text-muted">Contact</a></li>
                                    <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
                                </ul>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

 

templates/pamusika_web_market/contact.html
{% extends 'pamusika_web_market/base.html' %}


{% block title %} Contact {% endblock%}

{% block content %}
<h2>Contact view works</h2>
<h2>Contact view works</h2>
<h2>Contact view works</h2>
<h2>Contact view works</h2>
<h2>Contact view works</h2>
<h2>Contact view works</h2>

{% endblock %}

templates/pamusika_web_market/index.html
{% extends 'pamusika_web_market/base.html' %}


{% block title %} Home {% endblock%}

{% block content %}
<section class="newest-items">
    <div class="container py-5 pt-3">
        <div class="row py-5">
            <div class="col-lg-5 m-auto text-center">
                <h1>Newest Items</h1>
                <h6 style="color:red">Just in...</h6>
            </div>
        </div>
        <div class="row pt-2">
            <div class="col-lg-8 m-auto grey-color">
                <div class="row text-center pt-5 px-5">
                    {% for item in items %}
                    <div class="col-lg-4 mb-5 box-shadow">
                        <a class="links" href="{% url 'item:detail' item.id %}">
                            <img src="{{item.image.url}}" class="img-fluid" alt="photo of {{item}}" />
                            <h5>NEW</h5>
                            <h6>{{item}}</h6>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

<section class="Categories">
    <div class="container py-5">
        <div class="row py-5">
            <div class="col-lg-5 m-auto text-center">
                <h1>Categories</h1>
                <h6 style="color:red">Enjoy Organised Shopping with us...</h6>
            </div>
        </div>
        <div class="row pt-5">
            <div class="col-lg-10 m-auto grey-color p-5">
                <div class="row">
                    {% for category in categories%}
                    <div class="col-lg-4 ">
                        <div class="card border=0 bg-light mb-2">
                            <div class="card-body box-shadow">
                                <a class="links" href="{% url 'item:browse_items' %}?query={{query}}&category={{category.id}}">
                                    <div class="">
                                        <h4>{{category}}</h4>
                                        <p>{{category.items.count}} items</p>
                                    </div>
                                </a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/pamusika_web_market/login.html
{% extends 'pamusika_web_market/base.html' %}


{% block title %} Login {% endblock%}

{% block content %}
<div class="container-fluid  grey-color">
    <div class="row">
        <div class="col-lg-3 m-auto">
            <main class="form-signup w-100 m-auto">
                <form method="POST" action=".">
                    {% csrf_token %}
                    <h1 class="mb-4 mt-5 text-center">Pamusika</h1>
                    <h2 class="h3 mb-4 fw-normal text-center">Please Log in</h2>

                    <div class="form-floating">

                        <div class="mt-1">
                            <label for="floatingPassword">Username</label>
                            {{form.username}}
                        </div>

                    </div>
                    <div class="form-floating">
                        <div class="mt-1">
                            <label for="floatingPassword">Password</label>
                            {{form.password}}

                        </div>
                    {% if form.errors or form.non_field_errors%}
                    {% for field in form %}
                    {{field.errors}}
                    {% endfor %}

                    {{form.non_field_errors}}
                    {% endif %}

                    <div class="checkbox mb-3 mt-3 text-center">
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
                    <p class="text-center mt-5 mb-3 text-muted">pamusika&copy;2023</p>
                </form>
            </main>
        </div>
    </div>
</div>

{% endblock %}

templates/pamusika_web_market/signup.html
{% extends 'pamusika_web_market/base.html' %}


{% block title %} Sign Up {% endblock%}

{% block content %}
<div class="container-fluid  grey-color">
    <div class="row">
        <div class="col-lg-3 m-auto">
            <main class="form-signup w-100 m-auto">
                <form method="POST" action=".">
                    {% csrf_token %}
                    <h1 class="mb-4 mt-5 text-center">Pamusika</h1>
                    <h2 class="h3 mb-4 fw-normal text-center">Please Sign Up</h2>

                    <div class="form-floating">
                        
                        <div class="mt-1">
                            <label for="floatingPassword">Username</label>
                            {{form.username}}
                        </div> 
                     
                    </div>
                    <div class="form-floating">
                        <div class="mt-1">
                            <label for="floatingPassword">Email</label>
                            {{form.email}}

                        </div>
                    </div>
                    <div class="form-floating">
                        <div class="mt-1">
                            <label for="floatingPassword">Password</label>
                            {{form.password1}}

                        </div>
                    </div>
                    <div class="form-floating">
                        <div class="mt-1">
                            <label for="floatingPassword">Confirm Password</label>
                            {{form.password2}}
                        </div>
                    </div>
                    {% if form.errors or form.non_field_errors%}
                        {% for field in form %}
                            {{field.errors}}
                        {% endfor %}
                        
                        {{form.non_field_errors}}
                    {% endif %}

                    <div class="checkbox mb-3 mt-3 text-center">
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign Up</button>
                    <p class="text-center mt-5 mb-3 text-muted">pamusika&copy;2023</p>
                </form>
            </main>
        </div>
    </div>
</div>

{% endblock %}