conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'


urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    
]

item/urls.py
from django.urls import path, include
from . import views


# URL Patterns
app_name = 'item'
urlpatterns = [
    path('', views.browse_items, name='browse_items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

pamusika/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('pamusika_web_market.urls')),
    path('items/',include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('conversation/', include('conversation.urls')),
    path('admin/', admin.site.urls),
]

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Creating models for items.

class Category(models.Model):
    """This  class inherits from django models to create a custom category objects
    Django ORM is them used in the background to create the SQL table
    """
    name = models.CharField(max_length=255)

    # setting up class name plural
    class Meta:
        verbose_name_plural = 'Categories'
        # setting objects to be ordered by name
        ordering = ('name',)

    # setting up object name to return self.name
    def __str__(self):
        return self.name

class Item(models.Model):
    """This  class inherits from django models to create a custom Item objects
    Django ORM is them used in the background to create the SQL table
    """
    # linking the item to a category from the database.
    # on_delete modles.CASCADE means all items are deleted when the creator is deleted.
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField(default=0.00)
    image = models.ImageField(upload_to='static/images',blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    # linking the item to a user from the user database.
    # on_delete modles.CASCADE means all items are deleted when the creator is deleted.
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    # setting up object name to return self.name
    def __str__(self):
        return self.name



item/forms.py
from django import forms
from django import forms

from . models import Item

# creating a form classes
class NewItemForm(forms.ModelForm):
    """This  class inherits from django forms to create a custom form object for new items
    """
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        # adding styling and attributes to fields
        widgets = {
                'category': forms.Select(attrs={
                        'class': 'form-control'
                    }),
                'name': forms.TextInput(attrs={
                        'class': 'form-control'
                    }),
                'description': forms.Textarea(attrs={
                        'class': 'form-control'
                    }),
                'price': forms.TextInput(attrs={
                        'class': 'form-control'
                    }),
                'image': forms.FileInput(attrs={
                        'class': 'form-control'
                    }),
            }

class EditItemForm(forms.ModelForm):
    """This  class inherits from django forms to create a custom form object for edited items
    """
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        # adding styling and attributes to fields
        widgets = {
                'name': forms.TextInput(attrs={
                        'class': 'form-control'
                    }),
                'description': forms.Textarea(attrs={
                        'class': 'form-control'
                    }),
                'price': forms.TextInput(attrs={
                        'class': 'form-control'
                    }),
                'image': forms.FileInput(attrs={
                        'class': 'form-control'
                    }),
              
            }



item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Item, Category
from .forms import NewItemForm, EditItemForm

# Item views

def browse_items(request):
    """This  creates a view for the users to browse items

        :param request: HTTP protocol request

        :returns: renders the item/browse_items.html file

        :rtype: render"""
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    items = Item.objects.filter(is_sold=False)

    if query:
        # the double underscore is used in name__icontains to search for name that
        # contains the string in query
        # The Q from django.db.models is used to query over multiple fields
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))

    if category_id:
        items = Item.objects.filter(category_id=category_id)

    return render(request, 'item/browse_items.html',{
            'items': items,
            'query': query,
            'categories': categories,
            'category_id': int(category_id)
        })


def detail(request, pk):
    """This  creates a view for the users to see a selected item's details

        :param request: HTTP protocol request

        :returns: renders the 'item/detail.html' file

        :rtype: render
    """
    #getting item from database
    item = get_object_or_404(Item, pk=pk)

    #getting a list of related items from database
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
        })


@login_required
def new(request):
    """This  creates a view for the users add new items.
    A Django decorator is used to ensure the user is logged in first.

        :param request: HTTP protocol request

        :returns: renders the 'item/item_form.html' file

        :rtype: render
    """
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False) #not commiting to database yet Created_by field is required
            item.created_by = request.user #user is always required by the login_decorator
            item.save()

            # directing user to the detail page of the created item.
            return redirect('item:detail', pk=item.id)

    form = NewItemForm()

    return render(request, 'item/item_form.html', {
            'form_action': 'new',
            'form': form,
            'title': 'New Item',
        })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk,created_by=request.user)
    item.delete()

    return redirect('dashboard:index')


@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk,created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES,instance=item)

        if form.is_valid():
            item.save()

            # directing user to the detail page of the created item.
            return redirect('item:detail', pk=item.id)

    form = EditItemForm(instance=item)

    return render(request, 'item/item_form.html', {
            'form_action': 'edit',
            'item': item,
            'form': form,
            'title': 'Edit Item',
        })

templates/item/browse_items.html
{% extends 'pamusika_web_market/base.html' %}


{% block title %} Browse Items {% endblock%}

{% block content %}
<section class="Browse">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-1 dashboard">
                <div class="flex-shrink-0" style="width: 280px;">
                    
                    <ul class="list-unstyled">
                        <li class="mb-2">
                            <form action="{% url 'item:browse_items'%}" method="get">
                                <input name="query" type="text" value="{{query}}" class="form-control mb-2" id="floatingInput" placeholder="Search">
                                <button class="w-25 btn btn-sm btn-primary m-auto">Search</button>
                            </form>
                        </li>

                        <li class="mb-1">
                            <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#Category-collapse" aria-expanded="true">
                                Categories
                            </button>
                            <div class="collapse" id="Category-collapse">
                                <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                    {% for category in categories %}
                                    <li><a href="{% url 'item:browse_items' %}?query={{query}}&category={{category.id}}" class="link-dark d-inline-flex text-decoration-none rounded">{{category.name}}</a></li>
                                    {% endfor %}

                                </ul>
                            </div>
                        </li>

                        <li class="border-top my-3"></li>
              
                        <li class="mb-2">
                            <a href="{% url 'item:browse_items'%}">
                                <label class="text-dark mb-2">Clear Filters:</label>
                                <br />
                                <button class="w-25 btn btn-sm btn-warning m-auto">Clear</button>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            
   
            <div class="col-lg-10 m-auto">
                <div class="container py-5 pt-3">
                <div class="row py-5">
                    <div class="col-lg-5 m-auto text-center">
                        <h1>Browse Items</h1>
                        <h6 style="color:red">Just in...</h6>
                    </div>
                </div>
                <div class="row pt-2">
                    <div class="col-lg-8 m-auto grey-color">
                        <div class="row text-center pt-5 px-5">
                            {% for item in items %}
                            <div class="col-lg-4 mb-5 box-shadow">
                                <a class="links" href="{% url 'item:detail' item.id %}">
                                    <img src="{{item.image.url}}" class="img-fluid" alt="photo of {{item}}" />
                                    <h5>NEW</h5>
                                    <h6>{{item}}</h6>
                                </a>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/item/detail.html
{% extends 'pamusika_web_market/base.html' %}


{% block title %} {{item}} {% endblock%}

{% block content %}
<div class="container grey-color">
    <div class="row ">
        <div class="col-lg-5">
            <img src="{{item.image.url}}" class="img-fluid" alt="photo of {{item}}" />
        </div>
        <div class="col-lg-6 pt-5 mx-3">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">{{item}}</h3>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><strong>Price</strong>: R{{item.price}}</li>
                    <li class="list-group-item"><strong>Seller</strong>: {{item.created_by}}</li>
                    <li class="list-group-item"><strong>Description</strong>: <p>{{item.description}}</p></li>

                </ul>
                <div class="card-body">
                    {% if request.user == item.created_by %}
                    <p>This is your item.</p>
                    <a href="{% url 'item:edit' item.id %}" class="links"><button class="btn-primary btn-lg">Edit</button></a>
                    <a href="{% url 'item:delete' item.id %}" class="links"><button class="btn-danger btn-lg">Delete</button></a>

                    {% else %}
                    <a href="{% url 'conversation:new' item.id %}" class="links"><button class="btn-success btn-lg">Contact Seller</button></a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

<section class="Related-items">
    <div class="container py-1">
        <div class="row py-5">
            <div class="col-lg-5 m-auto text-center">
                <h1>You may also like</h1>
                <h6 style="color:red">Related items...</h6>
            </div>
        </div>
        <div class="row pt-5">
            <div class="col-lg-8 m-auto grey-color pt-5 px-5">
                <div class="row text-center">
                    {% for item in related_items %}
                    <div class="col-lg-4 mb-5 box-shadow">
                        <a class="links" href="{% url 'item:detail' item.id %}">
                            <img src="{{item.image.url}}" class="img-fluid" alt="photo of {{item}}" />
                            <h5>{{item}}</h5>
                            <p class="text-muted"><strong>Price</strong>: {{item.price}}</p>

                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}



templates/item/item_form.html
{% extends 'pamusika_web_market/base.html' %}


{% block title %} {{ title }} {% endblock%}

{% block content %}
<div class="container-fluid">
    <div class="row text-center">
        <div class="col-lg p-5">
            <h1 class="h1">{{ title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="container-fluid  grey-color">
                <div class="row">
                    <div class="col-lg-10 >
                        <main class="form-signup w-100 m-auto">
                            <form method="POST" action="." enctype="multipart/form-data"> <!--The enctype is to be able to upload images-->
                            {% csrf_token %}
                                <div class="form-floating">

                                    <div class="container-fluid mt-3">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <label>Category:</label>
                                            </div>
                                            <div class="col-lg">
                                                {% if form_action == 'new' %}
                                                {{form.category}}
                                                {% else %}
                                                {{form.category}} {{item.category}}
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="container-fluid mt-3">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <label>Name:</label>
                                            </div>
                                            <div class="col-lg">
                                                {{form.name}}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="container-fluid mt-3">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <label>Description:</label>
                                            </div>
                                            <div class="col-lg">
                                                {{form.description}}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="container-fluid mt-3">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <label>Price:</label>
                                            </div>
                                            <div class="col-lg">
                                                {{form.price}}
                                            </div>
                                        </div>
                                    </div>

                                    {% if form_action == 'edit'%}
                                    <div class="container-fluid mt-3">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <label>Sold:</label>
                                            </div>
                                            <div class="col-lg">
                                                {{form.is_sold}}
                                            </div>
                                        </div>
                                    </div>
                                    {% endif %}


                                    <div class="container-fluid mt-3">
                                        <div class="row">
                                            <div class="col-lg-3">
                                                <label>Image:</label>
                                            </div>
                                            <div class="col-lg">
                                                {{form.image}}
                                            </div>
                                        </div>
                                    </div>

                                    {% if form.errors or form.non_field_errors%}
                                    {% for field in form %}
                                    {{field.errors}}
                                    {% endfor %}

                                    {{form.non_field_errors}}
                                    {% endif %}

                                    <div class="text-center">
                                        <button class="w-50 mt-4 mb-5 btn btn-lg btn-success" type="submit">
                                            {% if form_action == 'new' %}
                                            Add Item
                                            {% else %}
                                            Apply
                                            {% endif %}
                                        </button>
                                    </div>
</form>
                        </main>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

<div class="container-fluid  grey-color">
    <div class="row">
        <div class="col-lg-3 m-auto">
            <main class="form-signup w-100 m-auto">
                <form method="POST" action=".">
                    <div class="form-floating">

                        <div class="mt-1">
                            <div class="row">
                                <label>Category:</label>
                                {{form.category}}
                            </div>
                        </div>

                   
                    {% if form.errors or form.non_field_errors%}
                    {% for field in form %}
                    {{field.errors}}
                    {% endfor %}

                    {{form.non_field_errors}}
                    {% endif %}

                    <button class="w-100 btn btn-lg btn-success" type="submit">Add Item</button>
                </form>
            </main>
        </div>
    </div>
</div>

